### PR TITLE
QUESTION: ``UIImage(named:)`` on iOS 17.2

### PR DESCRIPTION
**Pull request by darkThanBlack**
### Intro
First of all, I must express my sincere **THANKS** for your contribution [#3605](https://github.com/SDWebImage/SDWebImage/issues/3605) , This is the only relevant clue I've found.

### Desc
Next, please allow me to describe the problem I encountered. Considering [Privacy updates](https://developer.apple.com/news/?id=r1henawx), I upgraded my Xcode version to 15.1, iOS 17.2, but I found that when the image contains partially transparent content, func ``UIImage(named:)`` appears differently on iOS16 and iOS17, like this:

Sample image

### My question

This looks very similar to the bug you're dealing with, so I submitted this PR with a picture of the problem and sample code for reference.

What I would like to ask you is, **do you have any ideas to fix this problem quickly**, other than waiting for the iOS 17.3 update?

I'm not sure yet whether future apps built using Xcode 15.x will have problems on iOS 17.0 - 17.2. What a disaster.

### CODE REVIEW

**Comment by dreampiggy** [comment]
Because `UIImage(named:)` will finally use the **best performance solution for your current iPhone model** to load the image from xcassets (Assets Catalog)

Which means:

+ For JPEG/HEIF: Use `IOSurface` based CGImage, use YUV 4:2:0 color format, and then share memory between GPU and CPU, which saves 3/8 ram usage
+ For PNG: Use `CGImageSourceCreateFromURL` and loading data using `mmap`, then decode and send bitmap buffer to GPU (need extra copy).


So, if your image is PNG in assets catalog, which may not effected by this actually. Until you call that `imagePrepareForDisplay`, which trigger another pre-decode logic from internal `CMPhoto.framework`


For more details about Apple's internal optimization about image pipeline, check my blog: 

https://dreampiggy.com/tags/Image/
https://dreampiggy.com/2022/11/07/%E6%8E%A2%E7%A7%98%E8%B6%8A%E6%9D%A5%E8%B6%8A%E5%A4%8D%E6%9D%82%E7%9A%84ImageIO%E6%A1%86%E6%9E%B6/

**Comment by dreampiggy** [comment]
For your issue demo, I can try to check and see whether Apple change its pipeline to render the PNG image. I assume it does not contains issues.

The repo was used to report when you call `CGImageSourceCreateWithData` and then grab the bitmap buffer (using `CGDataProviderCopyData`) and used for other cases. Which will facing the wrong bitmap format bug.

But if you don't grab the bitmap buffer and directly send this CGImage into CALayer.contents, it should render correctly.

**Comment by darkThanBlack** [comment]
@dreampiggy 

**Thanks** again for your reply, but I did find a difference in performance before and after. Please allow me to describe the scene in detail again:

BBB

As you mentioned (actually I read that blog post at the beginning of the year, **awesome**), according to my personal understanding, in theory, when reading from ``assets``, compared with iOS 16 and 17, the image rendering process There shouldn't be big changes; 
even if there are, it should depend on the iOS version of the **actual** running device, but it doesn't seem to be the case from ``Mark1`` and ``Mark2``, which is another point that confuses me; 
since I lack the technical knowledge of dump or lldb, I can only request your Help;
I'm trying test more scenarios rightnow, but I haven't iPhone 17.2, So I not entirely sure if there are differences between 17.0.2 and 17.2;
If you have both Xcode 14.x and 15.x, you can try to reproduce Take a look at the ``Mark1`` and ``Mark2`` to make sure I didn't express the problem incorrectly.

**Comment by dreampiggy** [comment]
The Xcode 15.0-15.2 also contains a bug that convert the wrong Assets.car

It's another bug, but cause the similiar render 😼

You need to avoid add indexed PNG into Assets Catalog as well, or using Xcode 14 to build and submit Apps

**Comment by darkThanBlack** [comment]
@dreampiggy 
Good, good, good!
Thanks comment, according your keywords I founded some former about this issue, somebody suggest to convert PNG channel from 4 to 8, but didn't work.
Indeed, since these issues actually cannot be solved, I suspended upgrade to Xcode 15.2 and wait the release of Xcode 15.3.
In new project, I am totally turning to ``VectorDrawable + *.bundle`` .
BTW, one of my upgrade reasons is that, according [this news](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api), Apple actually requires me to complete the upgrade before **Spring 2024** (only Xcode 15.x can add privacy policy list), there's a lot of work to do here, I am doubtful this goal can be finish on time now. WHATEVER.

**Comment by darkThanBlack** [comment]
I followed up on this issue and created a new [Proj](https://github.com/darkThanBlack/Xcode15AssetsBug) to summarize the solution. Thanks for your help.

**Pull request closed without merging**
